

@baseurl=http://localhost:8080
@empId=EMP001
@currency=AED
@year=2023-24

### Get All Salaries: Working 
GET {{baseurl}}/api/salaries/all?employeeId={{empId}} HTTP/1.1
Content-Type: application/json

###1. **Upload Salary Excel**: Working 
POST {{baseurl}}/api/salaries/upload?employeeId={{empId}} HTTP/1.1
Content-Type: multipart/form-data

### 2. **Get Salary by Year**: Working 
GET {{baseurl}}/api/salaries/{{year}}?employeeId={{empId}}&baseCurrency={{currency}} HTTP/1.1
Content-Type: application/json

### 3. **Get Salary Trend**: Working
GET {{baseurl}}/api/salaries/trend?employeeId={{empId}}&baseCurrency={{currency}} HTTP/1.1
Content-Type: application/json

### 4. **Get Latest Salary**: Working
GET {{baseurl}}/api/salaries/latest?employeeId={{empId}}&baseCurrency={{currency}} HTTP/1.1
Content-Type: application/json

### 5. **Update Salary Hike**
PUT {{baseurl}}/api/salaries/{{year}}/hike?employeeId={{empId}} HTTP/1.1
Content-Type: application/json

{
    "hikePercentage": 10,
    "newVariableComponentHikePercentage": 10
}

### 6. **Record Company Switch**
POST {{baseurl}}/api/salaries/switch?employeeId={{empId}} HTTP/1.1
Content-Type: application/json
{
    "newCompanyName": "ABC pvt. ltd.",
    "financialYear": "2024-25",
    "fixedCTC": "300000",
    "variableComponent": 30000,
    "deductions": 6000,
    "currency": "AED"
}

### 7. **Compare Salaries Across Companies** : Working
GET {{baseurl}}/api/salaries/compare?employeeId={{empId}}&baseCurrency={{currency}}  HTTP/1.1
Content-Type: application/json
